### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by ponyatov** [nucleron/YAPLC#5]
Существует ли руководство по проекту в каком-нибудь виде?
как вариант: https://github.com/nucleron/YAPLC/wiki

**Comment by nucleron** [comment]
Что значит руководство по проекту?
Кто целевая аудитория?

**Comment by ponyatov** [comment]
Пользователи с инженерным/ИТ образованием, АСУшники и т.п.
Т.е. достаточно квалифицированные, чтобы работать на уровне программиста автоматики.

Есть несколько устройств на embedded Linux, одно из -- контроллер сбора данных.
Ищу opensource стек ПО для дополнения их прошивки функционалом, позволяющим интегрировать их в industrial сеть, и позволить пользователям разрабатывать пользовательские прошивки используя широко распространенный стек и инструментарий МЭК (закрытая часть ПО -- в виде бинарных библиотек).

**Comment by nucleron** [comment]
Тогда лучше воспользоваться "чистыми", без дополнений Beremiz/matiec.

Для связи с "внешним миром" можно использовать CanFestival, или Modbus, так же можно использовать Си/Python - расширения.

Доки на английском и полезные ссылки есть [тут](https://beremiz.org/doc), как и ссылка на youtube-канал.

Там же есть инструкции по сборке и запуску на различных ОС.

Неплохой мануал на Русском есть [тут](http://www.sm1820.ru/produktsiya/programmnoe-obespechenie/sistemy-programmirovaniya/item/3-beremiz.html), там довольно подробно расписано, как работать с Beremiz, в подробности связки с конкретным железом можно не смотреть.

**Comment by jubnzv** [comment]
> Неплохой мануал на Русском есть тут, там довольно подробно расписано, как работать с Beremiz, в подробности связки с конкретным железом можно не смотреть.

Дополню, что несколько обновлённая версия данного руководства в RST-формате доступна в [нашем репозитории](https://github.com/sm1820/beremiz/tree/master/doc). В html можно посмотреть [здесь](https://sm1820.github.io/beremiz/).

**Comment by nucleron** [comment]
Круто! 
А лицензия CC BY-SA 3.0?

**Comment by ponyatov** [comment]
Выглядит цивильно, а по установке на Linux в документации что-то появится в ближайшее время ?

**Comment by jubnzv** [comment]
> А лицензия CC BY-SA 3.0?

Да, документация доступна по [CC BY-SA 3.0](https://github.com/sm1820/beremiz/blob/master/doc/LICENSE).
