### ISSUE TITLE
About the trace variable！

### ISSUE THREAD

**Issue by frankgp** [nucleron/YAPLC#7]
This problems is about the BEREMIZ runtime debug functions. 
If there are many vairables in a PLC program.  such as 1000 DINT datas.
each cycle the PLC must make 4000 bytes debug-buffer and each get-variable command will
send 4000 bytes.
Is it right?

**Comment by nucleron** [comment]
No. Only registered (watched) variables are transfered the during debug session.

See RegisterDebugVariable and ResetDebugVariables functions in plc_debug.c template in targets subdir of beremiz dir.
