### ISSUE TITLE
Отладка

### ISSUE THREAD

**Issue by KazantsevEV** [nucleron/YAPLC#8]
Добрый день! Подскажите пожалуйста, в IDE YAPLC/Beremiz не нашел возможности установки breakpoint и пошаговой отладки, существует ли такой функционал?

**Comment by nucleron** [comment]
Добрый день. Такого функционала в Beremiz нет.

**Comment by KazantsevEV** [comment]
Спасибо за ответ. 
Вы не могли бы еще дать совет, есть ли какие то возможности самостоятельно разработать средства отладки или использовать уже существующие решения? Возможно у вас есть какие-нибудь мысли или соображения по данному поводу?

**Comment by nucleron** [comment]
К сожалению мыслей нет. Там отладчик сделан программным и для поддержки брейкпоинтов нужно менять код matiec и код отладчика beremiz...

**Comment by KazantsevEV** [comment]
Благодарю!
